{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeOperators #-}

-- | Servant API type definitions and handlers for the Auto-Knowledge feature
-- (P2-M5, EVA-80).
--
-- Two URL groups:
--   /api/programs/:id/knowledge  — program-scoped (list, create, search, refresh)
--   /api/knowledge/:entryId      — entry-scoped   (get, patch, delete, reset)
module Eva.Knowledge.Api
  ( KnowledgeByProgramAPI
  , KnowledgeByIdAPI
  , knowledgeByProgramHandlers
  , knowledgeByIdHandlers
  ) where

import Control.Monad.IO.Class (liftIO)
import Data.Aeson (encode)
import Data.Aeson.Types (Value (..))
import Data.List (nubBy)
import Data.Text (Text)
import Data.Time (getCurrentTime)
import qualified Data.UUID as UUID
import Data.UUID.V4 (nextRandom)
import Servant

import Eva.Api.Types (ApiError (..), CreateKnowledgeEntryReq (..), PatchKnowledgeEntryReq (..))
import Eva.App (AppEnv, AppM, runAppM)
import Eva.Core.Types (ProgramId (..))
import Eva.Knowledge.Extract (extractForSource)
import Eva.Knowledge.Query (search)
import Eva.Knowledge.Store
  ( deleteEntry
  , getEntry
  , insertEntry
  , listEntries
  , resetToAutoGenerated
  , updateEntry
  )
import Eva.Knowledge.Types

-- ---------------------------------------------------------------------------
-- API types
-- ---------------------------------------------------------------------------

type KnowledgeByProgramAPI =
  "api" :> "programs" :> Capture "id" Text :> "knowledge" :>
    (    Get '[JSON] [KnowledgeEntry]
    :<|> ReqBody '[JSON] CreateKnowledgeEntryReq :> PostCreated '[JSON] KnowledgeEntry
    :<|> "search"  :> ReqBody '[JSON] SearchQuery :> Post '[JSON] [SearchResult]
    :<|> "refresh" :> Post '[JSON] NoContent
    )

type KnowledgeByIdAPI =
  "api" :> "knowledge" :> Capture "entryId" Text :>
    (    Get '[JSON] KnowledgeEntry
    :<|> ReqBody '[JSON] PatchKnowledgeEntryReq :> Patch '[JSON] KnowledgeEntry
    :<|> DeleteNoContent
    :<|> "reset" :> Post '[JSON] KnowledgeEntry
    )

-- ---------------------------------------------------------------------------
-- Program-scoped handlers
-- ---------------------------------------------------------------------------

knowledgeByProgramHandlers :: AppEnv -> Server KnowledgeByProgramAPI
knowledgeByProgramHandlers env rawId =
       listH
  :<|> createH
  :<|> searchH
  :<|> refreshH
  where
    run :: AppM a -> Handler a
    run = liftIO . runAppM env

    pid :: ProgramId
    pid = ProgramId rawId

    -- GET /api/programs/:id/knowledge
    listH :: Handler [KnowledgeEntry]
    listH = run (listEntries pid)

    -- POST /api/programs/:id/knowledge
    createH :: CreateKnowledgeEntryReq -> Handler KnowledgeEntry
    createH req = do
      eid <- liftIO (KnowledgeEntryId . UUID.toText <$> nextRandom)
      now <- liftIO getCurrentTime
      let cat = maybe CategorySummary id (ckerCategory req)
          entry = KnowledgeEntry
            { knowledgeEntryId              = eid
            , knowledgeEntrySourceType      = SourceManual
            , knowledgeEntrySourceId        = Nothing
            , knowledgeEntryProgramId       = Just pid
            , knowledgeEntryCategory        = cat
            , knowledgeEntryTitle           = ckerTitle req
            , knowledgeEntryContent         = ckerContent req
            , knowledgeEntryOriginalContent = Nothing
            , knowledgeEntryMetadata        = Null
            , knowledgeEntryConfidence      = 1.0
            , knowledgeEntryIsEdited        = True
            , knowledgeEntryCreatedAt       = now
            , knowledgeEntryUpdatedAt       = now
            , knowledgeEntryScannedAt       = now
            }
      run (insertEntry entry)
      pure entry

    -- POST /api/programs/:id/knowledge/search
    -- The programId in the request body is overridden by the URL parameter.
    searchH :: SearchQuery -> Handler [SearchResult]
    searchH sq = run (search sq { searchQueryProgramId = Just pid })

    -- POST /api/programs/:id/knowledge/refresh
    -- Finds all unique (sourceType, sourceId) pairs for non-manual entries in
    -- this program and re-runs extraction for each one.
    refreshH :: Handler NoContent
    refreshH = do
      entries <- run (listEntries pid)
      let sources = nubBy sameSource
            [ (knowledgeEntrySourceType e, knowledgeEntrySourceId e)
            | e <- entries
            , knowledgeEntrySourceType e /= SourceManual
            ]
      mapM_ (\(srcType, srcId) -> run (extractForSource srcType srcId pid)) sources
      pure NoContent
      where
        sameSource (t1, i1) (t2, i2) = t1 == t2 && i1 == i2

-- ---------------------------------------------------------------------------
-- Entry-scoped handlers
-- ---------------------------------------------------------------------------

knowledgeByIdHandlers :: AppEnv -> Server KnowledgeByIdAPI
knowledgeByIdHandlers env rawId =
       getH
  :<|> patchH
  :<|> deleteH
  :<|> resetH
  where
    run :: AppM a -> Handler a
    run = liftIO . runAppM env

    requireEntry :: Handler KnowledgeEntry
    requireEntry = do
      me <- run (getEntry rawId)
      case me of
        Nothing -> throwError err404 { errBody = encode (ApiError "Knowledge entry not found") }
        Just e  -> pure e

    -- GET /api/knowledge/:entryId
    getH :: Handler KnowledgeEntry
    getH = requireEntry

    -- PATCH /api/knowledge/:entryId
    patchH :: PatchKnowledgeEntryReq -> Handler KnowledgeEntry
    patchH req = do
      e   <- requireEntry
      now <- liftIO getCurrentTime
      let e' = e
            { knowledgeEntryTitle     = maybe (knowledgeEntryTitle e) id (pkerTitle req)
            , knowledgeEntryContent   = maybe (knowledgeEntryContent e) id (pkerContent req)
            , knowledgeEntryIsEdited  = True
            , knowledgeEntryUpdatedAt = now
            }
      run (updateEntry e')
      pure e'

    -- DELETE /api/knowledge/:entryId
    deleteH :: Handler NoContent
    deleteH = do
      _ <- requireEntry
      run (deleteEntry rawId)
      pure NoContent

    -- POST /api/knowledge/:entryId/reset
    resetH :: Handler KnowledgeEntry
    resetH = do
      _ <- requireEntry
      run (resetToAutoGenerated rawId)
      requireEntry
