{-# LANGUAGE OverloadedStrings #-}

-- | CRUD functions for knowledge_entries.
-- The FTS index (knowledge_fts) is maintained entirely by the 3 sync triggers
-- created in Eva.Persistence.Migration — this module never queries FTS directly.
module Eva.Knowledge.Store
  ( insertEntry
  , updateEntry
  , deleteEntry
  , getEntry
  , listEntries
  , listBySource
  , deleteNonEditedBySource
  , resetToAutoGenerated
  ) where

import Control.Monad.IO.Class (liftIO)
import Data.Aeson (FromJSON, ToJSON, eitherDecodeStrict, encode, toJSON)
import Data.Aeson.Types (parseEither, parseJSON)
import qualified Data.ByteString.Lazy as BL
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.Time (getCurrentTime)
import Database.Persist.Sql
  ( Entity (..)
  , SelectOpt (..)
  , delete
  , deleteWhere
  , get
  , insertKey
  , selectList
  , update
  , (=.)
  , (==.)
  )

import Eva.App (AppM)
import Eva.Core.Types (ProgramId (..))
import Eva.Knowledge.Types
import Eva.Persistence.Queries (runDb)
import Eva.Persistence.Schema

-- ---------------------------------------------------------------------------
-- Encoding helpers (mirrors Queries.hs — not re-exported from there)
-- ---------------------------------------------------------------------------

toJsonText :: ToJSON a => a -> Text
toJsonText = TE.decodeUtf8 . BL.toStrict . encode

fromJsonText :: FromJSON a => Text -> Either String a
fromJsonText = eitherDecodeStrict . TE.encodeUtf8

encodeState :: ToJSON a => a -> Text
encodeState = T.dropAround (== '"') . toJsonText

decodeState :: FromJSON a => Text -> Either String a
decodeState t = parseEither parseJSON (toJSON t)

-- ---------------------------------------------------------------------------
-- ID helpers
-- ---------------------------------------------------------------------------

toKnowledgeRowId :: KnowledgeEntryId -> KnowledgeEntryRowId
toKnowledgeRowId (KnowledgeEntryId t) = KnowledgeEntryRowKey t

fromKnowledgeRowId :: KnowledgeEntryRowId -> KnowledgeEntryId
fromKnowledgeRowId (KnowledgeEntryRowKey t) = KnowledgeEntryId t

toProgramRowIdLocal :: ProgramId -> ProgramRowId
toProgramRowIdLocal (ProgramId t) = ProgramRowKey t

-- ---------------------------------------------------------------------------
-- Row <-> Domain
-- ---------------------------------------------------------------------------

entryToRow :: KnowledgeEntry -> KnowledgeEntryRow
entryToRow e =
  KnowledgeEntryRow
    { knowledgeEntryRowSourceType      = encodeState (knowledgeEntrySourceType e)
    , knowledgeEntryRowSourceId        = knowledgeEntrySourceId e
    , knowledgeEntryRowProgramId       = toProgramRowIdLocal <$> knowledgeEntryProgramId e
    , knowledgeEntryRowCategory        = encodeState (knowledgeEntryCategory e)
    , knowledgeEntryRowTitle           = knowledgeEntryTitle e
    , knowledgeEntryRowContent         = knowledgeEntryContent e
    , knowledgeEntryRowOriginalContent = knowledgeEntryOriginalContent e
    , knowledgeEntryRowMetadata        = toJsonText (knowledgeEntryMetadata e)
    , knowledgeEntryRowConfidence      = knowledgeEntryConfidence e
    , knowledgeEntryRowIsEdited        = knowledgeEntryIsEdited e
    , knowledgeEntryRowCreatedAt       = knowledgeEntryCreatedAt e
    , knowledgeEntryRowUpdatedAt       = knowledgeEntryUpdatedAt e
    , knowledgeEntryRowScannedAt       = knowledgeEntryScannedAt e
    }

entryFromRow :: KnowledgeEntryRowId -> KnowledgeEntryRow -> Either String KnowledgeEntry
entryFromRow rowId row = do
  src  <- decodeState (knowledgeEntryRowSourceType row)
  cat  <- decodeState (knowledgeEntryRowCategory row)
  meta <- fromJsonText (knowledgeEntryRowMetadata row)
  pure KnowledgeEntry
    { knowledgeEntryId              = fromKnowledgeRowId rowId
    , knowledgeEntrySourceType      = src
    , knowledgeEntrySourceId        = knowledgeEntryRowSourceId row
    , knowledgeEntryProgramId       = fmap (\(ProgramRowKey t) -> ProgramId t)
                                        (knowledgeEntryRowProgramId row)
    , knowledgeEntryCategory        = cat
    , knowledgeEntryTitle           = knowledgeEntryRowTitle row
    , knowledgeEntryContent         = knowledgeEntryRowContent row
    , knowledgeEntryOriginalContent = knowledgeEntryRowOriginalContent row
    , knowledgeEntryMetadata        = meta
    , knowledgeEntryConfidence      = knowledgeEntryRowConfidence row
    , knowledgeEntryIsEdited        = knowledgeEntryRowIsEdited row
    , knowledgeEntryCreatedAt       = knowledgeEntryRowCreatedAt row
    , knowledgeEntryUpdatedAt       = knowledgeEntryRowUpdatedAt row
    , knowledgeEntryScannedAt       = knowledgeEntryRowScannedAt row
    }

-- ---------------------------------------------------------------------------
-- CRUD
-- ---------------------------------------------------------------------------

insertEntry :: KnowledgeEntry -> AppM ()
insertEntry e = runDb $
  insertKey (toKnowledgeRowId (knowledgeEntryId e)) (entryToRow e)

updateEntry :: KnowledgeEntry -> AppM ()
updateEntry e = runDb $
  update (toKnowledgeRowId (knowledgeEntryId e))
    [ KnowledgeEntryRowSourceType      =. encodeState (knowledgeEntrySourceType e)
    , KnowledgeEntryRowSourceId        =. knowledgeEntrySourceId e
    , KnowledgeEntryRowProgramId       =. (toProgramRowIdLocal <$> knowledgeEntryProgramId e)
    , KnowledgeEntryRowCategory        =. encodeState (knowledgeEntryCategory e)
    , KnowledgeEntryRowTitle           =. knowledgeEntryTitle e
    , KnowledgeEntryRowContent         =. knowledgeEntryContent e
    , KnowledgeEntryRowOriginalContent =. knowledgeEntryOriginalContent e
    , KnowledgeEntryRowMetadata        =. toJsonText (knowledgeEntryMetadata e)
    , KnowledgeEntryRowConfidence      =. knowledgeEntryConfidence e
    , KnowledgeEntryRowIsEdited        =. knowledgeEntryIsEdited e
    , KnowledgeEntryRowUpdatedAt       =. knowledgeEntryUpdatedAt e
    , KnowledgeEntryRowScannedAt       =. knowledgeEntryScannedAt e
    ]

deleteEntry :: Text -> AppM ()
deleteEntry eid = runDb $ delete (KnowledgeEntryRowKey eid)

getEntry :: Text -> AppM (Maybe KnowledgeEntry)
getEntry eid = runDb $ do
  let rowId = KnowledgeEntryRowKey eid
  mRow <- get rowId
  case mRow of
    Nothing  -> pure Nothing
    Just row -> case entryFromRow rowId row of
      Left err -> fail $ "getEntry: " <> err
      Right e  -> pure (Just e)

listEntries :: ProgramId -> AppM [KnowledgeEntry]
listEntries pid = runDb $ do
  entities <- selectList
    [KnowledgeEntryRowProgramId ==. Just (toProgramRowIdLocal pid)]
    [Asc KnowledgeEntryRowCreatedAt]
  traverse decode entities
  where
    decode (Entity k row) = case entryFromRow k row of
      Left err -> fail $ "listEntries: " <> err
      Right e  -> pure e

listBySource :: KnowledgeSourceType -> Maybe Text -> ProgramId -> AppM [KnowledgeEntry]
listBySource srcType srcId pid = runDb $ do
  entities <- selectList
    [ KnowledgeEntryRowSourceType ==. encodeState srcType
    , KnowledgeEntryRowSourceId   ==. srcId
    , KnowledgeEntryRowProgramId  ==. Just (toProgramRowIdLocal pid)
    ]
    [Asc KnowledgeEntryRowCreatedAt]
  traverse decode entities
  where
    decode (Entity k row) = case entryFromRow k row of
      Left err -> fail $ "listBySource: " <> err
      Right e  -> pure e

-- | Delete all non-edited entries for a given source + program.
-- Preserves any entry where is_edited = True.
-- Called at the start of a refresh cycle to remove stale auto-generated entries.
deleteNonEditedBySource :: KnowledgeSourceType -> Maybe Text -> ProgramId -> AppM ()
deleteNonEditedBySource srcType srcId pid = runDb $
  deleteWhere
    [ KnowledgeEntryRowSourceType ==. encodeState srcType
    , KnowledgeEntryRowSourceId   ==. srcId
    , KnowledgeEntryRowProgramId  ==. Just (toProgramRowIdLocal pid)
    , KnowledgeEntryRowIsEdited   ==. False
    ]

-- | Restore a knowledge entry to its auto-generated content.
-- Sets `content` to `originalContent` and clears `isEdited`.
-- No-op if the entry does not exist or has no stored original content.
resetToAutoGenerated :: Text -> AppM ()
resetToAutoGenerated eid = do
  now <- liftIO getCurrentTime
  runDb $ do
    let rowId = KnowledgeEntryRowKey eid
    mRow <- get rowId
    case mRow of
      Nothing  -> pure ()
      Just row -> case knowledgeEntryRowOriginalContent row of
        Nothing       -> pure ()
        Just original ->
          update rowId
            [ KnowledgeEntryRowContent   =. original
            , KnowledgeEntryRowIsEdited  =. False
            , KnowledgeEntryRowUpdatedAt =. now
            ]
